# Generated by Django 5.2.7 on 2025-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emoji", models.CharField(max_length=10)),
                ("time", models.CharField(default="Received just now", max_length=50)),
            ],
        ),
    ]
