# Generated by Django 5.2.7 on 2025-10-22 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapchat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="time",
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
