# Generated by Django 5.2.7 on 2025-10-22 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapchat", "0002_alter_chat_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
